import localFont from "next/font/local";
import { Onest } from "next/font/google";
import {
  ClerkProvider
} from '@clerk/nextjs'
import "./globals.css";
import Header from "@/components/header";

const inter = Onest({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider touchSession={false} >
      <html lang="en">
        <body
          className={`${inter.className} bg-primary text-foreground`}
        >
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>

  );
}
